name: coffee_maker
description: A coffee image browser app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  coffee_photos_repository:
    path: packages/coffee_photos_repository
  connectivity_plus: ^6.0.5
  dio: ^5.9.0
  environment:
    path: packages/environment
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.0.2
  go_router: ^16.2.4
  hive_ce_flutter: ^2.3.2
  http: ^1.2.2
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  network:
    path: packages/network
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  stack_trace: ^1.12.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.6.2
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
