name: version_manager
description: A Dart tool to manage versions across all pubspec.yaml files in the Coffee Maker project
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.6.0
  logging: ^1.3.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
