include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/src/*.g.dart
    - lib/src/models/*.g.dart
    - lib/src/models/*.freezed.dart
    - test/src/*.g.dart
    - test/src/*.freezed.dart
