name: coffee_photos_repository
description: The data layer to load beautiful coffee photos
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hive_ce: ^2.14.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  retrofit: ^4.7.3

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.6.2
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.6
  very_good_analysis: ^10.0.0
