name: environment
description: Environment configuration package for Coffee Maker app
version: 1.0.1+2
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  envied: ^1.0.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.7.1
  envied_generator: ^1.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
